version: '3'
services:
  app:
    container_name: full_app
    build: .
    ports:
      - 80:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - fullstack-mysql
    networks:
      - fullstack


  fullstack-mysql:
    image: mysql:latest
    container_name: full_db_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_HOST=fullstack-mysql
      - MYSQL_USER=iqbal
      - MYSQL_PASSWORD=iqbal
      - MYSQL_DATABASE= edetect
      - MYSQL_ROOT_PASSWORD=iqbal
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - fullstack

volumes:
  api:
  database_mysql:

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge