version: '3'
services:
  app:
    container_name: full_app
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - fullstack-mysql
    networks:
      - fullstack


  fullstack-mysql:
    image: mysql:5.7
    container_name: full_db_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_HOST=localhost
      - MYSQL_USER=root
      - MYSQL_PASSWORD=toor
      - MYSQL_DATABASE= e-detect
      - MYSQL_ROOT_PASSWORD=toor
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - fullstack

volumes:
  api:
  database_mysql:

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge