basePath: /business
definitions:
  response.ApiResponse:
    properties:
      data: {}
      status:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
  description: Aplikasi untuki mendeteksi nomor rekening dan telepon yang melakukan
    penipuan
  title: e-detect
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/json
      description: Retrieve list of all users
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ApiResponse'
      summary: Get all users
      tags:
      - accounts
swagger: "2.0"
